global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'frontend'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:5000']
  - job_name: 'project'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:5010']
  - job_name: 'timetracking'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:5020']
